### ISSUE TITLE
你这个怎么使用的呀？

### ISSUE THREAD

**Issue by scc172fly** [galigalikun/unpack-spine-atlas#2]
我怎么就没跑起来呢？还需要依赖其他的么？可以出个使用教程吗？还有你这个没有针对一些发杂的情况，图片目录都是一级的，当图片文件夹有二级目录的话应该不能很好的归类。

go run main.go
panic: open skeleton.atlas.txt: The system cannot find the file specified.

goroutine 1 [running]:
main.Work({0xb34d4c, 0xc0000422e0}, {0xb32567, 0x6})
        G:/unpack-spine-atlas/main.go:370 +0x1e5
main.main()
        G:/unpack-spine-atlas/main.go:395 +0x16b
exit status 2

**Comment by galigalikun** [comment]
hi

Usage

option
--in atlas file path (default skeleton.atlas.txt)
--out output dir path (default result)

ex)

go run main.go --in dragon-ess.atlas --out out

**Comment by scc172fly** [comment]
There is still an error! 
System: windows10
go version go1.17, windows / AMD64

go run main.go --in dragon-ess.atlas --out out
rotate-> true
rotate true!!
rotate-> true
rotate true!!
rotate-> false
rotate-> false
rotate-> true
rotate true!!
rotate-> false
rotate-> true
rotate true!!
rotate-> false
rotate-> false
rotate-> false
rotate-> true
rotate true!!
rotate-> true
rotate true!!
rotate-> true
rotate true!!
rotate-> false
rotate-> false
rotate-> false
rotate-> true
rotate true!!
rotate-> false
rotate-> true
rotate true!!
rotate-> false
rotate-> true
rotate true!!
rotate-> true
rotate true!!
rotate-> false
rotate-> false
rotate-> false
rotate-> false
rotate-> true
rotate true!!
rotate-> true
rotate true!!
rotate-> false
rotate-> false
rotate-> false
rotate-> false
rotate-> false
rotate-> false
rotate-> false
rotate-> true
rotate true!!
rotate-> false
rotate-> true
rotate true!!
rotate-> true
rotate true!!
rotate-> false
: The filename, directory name, or volume label syntax is incorrect.

**Comment by scc172fly** [comment]
I used the last submitted version and can use it normally.
